name: Kcrypto
version: '1.0.0'
main: com.kcrp.kcrypto.KcryptoPlugin
api-version: '1.21'
folia-supported: true
description: Folia crypto-economy plugin for KCRP.
authors: [KCRP]


commands:
  kcrypto:
    description: Admin commands for Kcrypto.
    usage: /kcrypto <add|remove|admin|track>
    permission: kcrypto.admin.all
  crypto:
    description: Player commands for Kcrypto.
    usage: /crypto <wallet|pay|withdraw>
    permission: kcrypto.member

permissions:
  kcrypto.member:
    description: Accès joueur de base (wallet, pay).
    default: true
  kcrypto.owner:
    description: Accès aux commandes de gestion de machine (whitelist/blacklist).
    default: false
  kcrypto.blanchisseur:
    description: Accès au PNJ Blanchisseur et à /crypto withdraw.
    default: false
  kcrypto.admin.all:
    description: Accès administratif complet (add, remove, admin, track).
    default: op
